//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyVersionAttribute("2.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.0.0-beta")]

// Generated by the MSBuild WriteCodeFragment class on 2013-12-05 16:01:59.

